# Generated by Django 5.0.14 on 2026-05-16 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("period", models.CharField(default="daily", max_length=20)),
                ("total_activities", models.PositiveIntegerField(default=0)),
                ("user_activities", models.PositiveIntegerField(default=0)),
                ("admin_activities", models.PositiveIntegerField(default=0)),
                ("system_activities", models.PositiveIntegerField(default=0)),
                ("property_actions", models.PositiveIntegerField(default=0)),
                ("booking_actions", models.PositiveIntegerField(default=0)),
                ("payment_actions", models.PositiveIntegerField(default=0)),
                ("user_actions", models.PositiveIntegerField(default=0)),
                ("successful_activities", models.PositiveIntegerField(default=0)),
                ("failed_activities", models.PositiveIntegerField(default=0)),
                ("low_severity", models.PositiveIntegerField(default=0)),
                ("medium_severity", models.PositiveIntegerField(default=0)),
                ("high_severity", models.PositiveIntegerField(default=0)),
                ("critical_severity", models.PositiveIntegerField(default=0)),
                ("top_actors", models.JSONField(blank=True, default=dict)),
                ("top_targets", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Activity Summary",
                "verbose_name_plural": "Activity Summaries",
                "ordering": ["-date"],
                "unique_together": {("date", "period")},
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("register", "User Registration"),
                            ("password_change", "Password Change"),
                            ("profile_update", "Profile Update"),
                            ("property_create", "Property Created"),
                            ("property_update", "Property Updated"),
                            ("property_delete", "Property Deleted"),
                            ("property_publish", "Property Published"),
                            ("property_unpublish", "Property Unpublished"),
                            ("property_view", "Property Viewed"),
                            ("property_inquiry", "Property Inquiry"),
                            ("property_favorite", "Property Favorited"),
                            ("property_review", "Property Reviewed"),
                            ("booking_create", "Booking Created"),
                            ("booking_update", "Booking Updated"),
                            ("booking_cancel", "Booking Cancelled"),
                            ("booking_confirm", "Booking Confirmed"),
                            ("booking_check_in", "Check In"),
                            ("booking_check_out", "Check Out"),
                            ("payment_process", "Payment Processed"),
                            ("payment_refund", "Payment Refunded"),
                            ("admin_login", "Admin Login"),
                            ("admin_action", "Admin Action"),
                            ("moderation_action", "Moderation Action"),
                            ("system_maintenance", "System Maintenance"),
                            ("system_error", "System Error"),
                            ("system_warning", "System Warning"),
                            ("api_call", "API Call"),
                            ("file_upload", "File Upload"),
                            ("email_sent", "Email Sent"),
                            ("notification_sent", "Notification Sent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("actor_user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("target_name", models.CharField(blank=True, max_length=255)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("audit_trail", models.JSONField(blank=True, default=list)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="activity_ac_action__297bb3_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="activity_ac_actor_i_3adaf1_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="activity_ac_target__16e969_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="activity_ac_severit_7a1712_idx"
                    ),
                    models.Index(
                        fields=["status"], name="activity_ac_status_e1f59f_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_ac_content_ee8889_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("data_export", "Data Export"),
                            ("bulk_delete", "Bulk Delete"),
                            ("permission_change", "Permission Change"),
                            ("system_config_change", "System Configuration Change"),
                            ("sensitive_data_access", "Sensitive Data Access"),
                            ("account_deactivation", "Account Deactivation"),
                            ("payment_manipulation", "Payment Manipulation"),
                            ("content_moderation", "Content Moderation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("actor_role", models.CharField(max_length=50)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=255)),
                ("target_details", models.JSONField(blank=True, default=dict)),
                ("justification", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("compliance_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("requires_review", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="activity_au_action_8bb671_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="activity_au_actor_i_ec802f_idx",
                    ),
                    models.Index(
                        fields=["requires_review"],
                        name="activity_au_require_542cde_idx",
                    ),
                    models.Index(
                        fields=["verified_at"], name="activity_au_verifie_67df6e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed Login"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("data_breach_attempt", "Data Breach Attempt"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("sql_injection_attempt", "SQL Injection Attempt"),
                            ("xss_attempt", "XSS Attempt"),
                            ("brute_force_attempt", "Brute Force Attempt"),
                            ("unusual_login_location", "Unusual Login Location"),
                            ("account_lockout", "Account Lockout"),
                            ("password_reset", "Password Reset"),
                            ("api_key_compromised", "API Key Compromised"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("url", models.URLField(blank=True)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                (
                    "threat_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="AI-calculated threat score (0-100)",
                        max_digits=5,
                    ),
                ),
                ("is_false_positive", models.BooleanField(default=False)),
                ("analysis_notes", models.TextField(blank=True)),
                ("blocked", models.BooleanField(default=False)),
                ("alerted", models.BooleanField(default=False)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("immediate", "Immediate Action"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="activity_se_event_t_5995d3_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="activity_se_risk_le_ac5d95_idx"
                    ),
                    models.Index(
                        fields=["threat_score"], name="activity_se_threat__44dcab_idx"
                    ),
                    models.Index(
                        fields=["blocked"], name="activity_se_blocked_b36956_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="activity_se_ip_addr_6b84e6_idx"
                    ),
                ],
            },
        ),
    ]
