# Generated by Django 5.0.14 on 2026-05-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("condo", "Condominium"),
                    ("townhouse", "Townhouse"),
                    ("studio", "Studio"),
                    ("loft", "Loft"),
                    ("penthouse", "Penthouse"),
                    ("commercial", "Commercial"),
                    ("land", "Land"),
                    ("camping_site", "Camping Site"),
                    ("hotel_room", "Hotel Room"),
                    ("other", "Other"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
