# Generated by Django 5.0.14 on 2026-05-16 22:26

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.CharField(max_length=255, unique=True)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Search Suggestion",
                "verbose_name_plural": "Search Suggestions",
                "ordering": ["-frequency", "term"],
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=255, unique=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                (
                    "trending_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Popular Search",
                "verbose_name_plural": "Popular Searches",
                "ordering": ["-search_count", "-trending_score"],
                "indexes": [
                    models.Index(fields=["term"], name="search_popu_term_95e658_idx"),
                    models.Index(
                        fields=["search_count"], name="search_popu_search__15d115_idx"
                    ),
                    models.Index(
                        fields=["trending_score"], name="search_popu_trendin_721555_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertySearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("title_vector", models.TextField(blank=True)),
                ("description_vector", models.TextField(blank=True)),
                ("location_vector", models.TextField(blank=True)),
                ("amenities_vector", models.TextField(blank=True)),
                ("price_range", models.CharField(blank=True, max_length=50)),
                ("bedroom_range", models.CharField(blank=True, max_length=50)),
                ("property_type", models.CharField(blank=True, max_length=50)),
                ("last_indexed", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Search Index",
                "verbose_name_plural": "Property Search Indexes",
                "indexes": [
                    models.Index(
                        fields=["search_vector"], name="search_prop_search__2571a3_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="search_prop_is_acti_9776c9_idx"
                    ),
                    models.Index(
                        fields=["price_range"], name="search_prop_price_r_b7b7e2_idx"
                    ),
                    models.Index(
                        fields=["bedroom_range"], name="search_prop_bedroom_0ce20d_idx"
                    ),
                    models.Index(
                        fields=["property_type"], name="search_prop_propert_ecf50f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "search_params",
                    models.JSONField(help_text="Saved search parameters"),
                ),
                ("email_notifications", models.BooleanField(default=False)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="search_save_user_id_49e8a0_idx",
                    ),
                    models.Index(
                        fields=["last_run_at"], name="search_save_last_ru_333898_idx"
                    ),
                ],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("query", models.CharField(blank=True, max_length=500)),
                ("filters", models.JSONField(default=dict)),
                ("sort_by", models.CharField(blank=True, max_length=100)),
                ("page", models.PositiveIntegerField(default=1)),
                ("result_count", models.PositiveIntegerField(default=0)),
                (
                    "execution_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Search execution time in seconds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Search source (web, mobile, api)",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="search_sear_user_id_2836be_idx",
                    ),
                    models.Index(fields=["query"], name="search_sear_query_eedf16_idx"),
                    models.Index(
                        fields=["created_at"], name="search_sear_created_819524_idx"
                    ),
                    models.Index(
                        fields=["source"], name="search_sear_source_99fb23_idx"
                    ),
                ],
            },
        ),
    ]
