# Generated by Django 5.0.14 on 2026-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("guest", "Guest"), ("host", "Host"), ("agent", "Agent")],
                default="guest",
                max_length=20,
            ),
        ),
    ]
