# Generated by Django 5.0.14 on 2026-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("host", "Host"),
                    ("agent", "Agent"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                ],
                default="guest",
                max_length=20,
            ),
        ),
    ]
