# Generated by Django 5.0.14 on 2026-05-05 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ListingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="mobile_money",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("golis", "Golis"),
                            ("hormuud", "Hormuud Telecom"),
                            ("telesom", "Telesom"),
                            ("somtel", "Somtel"),
                            ("amtelt", "Amtel"),
                        ],
                        default="golis",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_data", models.JSONField(blank=True, default=dict)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_payment",
                        to="kiro.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Payment",
                "verbose_name_plural": "Listing Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "status"],
                        name="kiro_listin_propert_64b04b_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="kiro_listin_user_id_edfd86_idx"
                    ),
                    models.Index(
                        fields=["transaction_reference"],
                        name="kiro_listin_transac_daf98e_idx",
                    ),
                ],
            },
        ),
    ]
