# Generated by Django 5.0.14 on 2026-05-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0004_alter_payment_options_alter_payment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingpayment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card Payment"), ("mobile_money", "Mobile Money")],
                default="mobile_money",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listingpayment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
