# Generated by Django 5.0.14 on 2026-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0005_alter_listingpayment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
