# Generated by Django 5.0.14 on 2026-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0006_payment_commission_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("golis", "Golis"),
                    ("hormuud", "Hormuud Telecom"),
                    ("telesom", "Telesom"),
                    ("somtel", "Somtel"),
                    ("amtelt", "Amtel"),
                ],
                default="golis",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card Payment"), ("mobile_money", "Mobile Money")],
                default="mobile_money",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("rented", "Rented"),
                    ("sold", "Sold"),
                    ("inactive", "Inactive"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ListingPayment",
        ),
    ]
