# Generated by Django 5.0.14 on 2026-05-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("kiro", "0008_alter_booking_cancelled_by_alter_booking_guest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="property",
        ),
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiro_review",
                to="bookings.booking",
            ),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("condo", "Condominium"),
                    ("townhouse", "Townhouse"),
                    ("studio", "Studio"),
                    ("loft", "Loft"),
                    ("penthouse", "Penthouse"),
                    ("commercial", "Commercial"),
                    ("land", "Land"),
                    ("camping_site", "Camping Site"),
                    ("hotel_room", "Hotel Room"),
                    ("other", "Other"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
