# Generated by Django 5.0.14 on 2026-05-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiro", "0009_remove_booking_cancelled_by_remove_booking_guest_and_more"),
        ("payment", "0002_alter_payment_booking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
