# Generated by Django 5.0.14 on 2026-05-10 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("properties", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_users", "Total Users"),
                            ("active_users", "Active Users"),
                            ("total_properties", "Total Properties"),
                            ("active_properties", "Active Properties"),
                            ("total_bookings", "Total Bookings"),
                            ("monthly_revenue", "Monthly Revenue"),
                            ("total_views", "Total Views"),
                            ("conversion_rate", "Conversion Rate"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("value_text", models.CharField(blank=True, max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Metric",
                "verbose_name_plural": "Dashboard Metrics",
            },
        ),
        migrations.CreateModel(
            name="PropertyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                (
                    "view_duration_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average view duration in seconds",
                        max_digits=8,
                    ),
                ),
                ("inquiries_count", models.PositiveIntegerField(default=0)),
                ("favorites_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("bookings_count", models.PositiveIntegerField(default=0)),
                (
                    "booking_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of views that convert to bookings",
                        max_digits=5,
                    ),
                ),
                ("last_viewed", models.DateTimeField(blank=True, null=True)),
                (
                    "trending_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Trending score based on recent activity",
                        max_digits=8,
                    ),
                ),
                (
                    "search_rank_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average search ranking",
                        max_digits=5,
                    ),
                ),
                (
                    "click_through_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="CTR from search results",
                        max_digits=5,
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Analytics",
                "verbose_name_plural": "Property Analytics",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user_activity", "User Activity Report"),
                            ("property_performance", "Property Performance Report"),
                            ("revenue", "Revenue Report"),
                            ("booking", "Booking Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.FileField(blank=True, upload_to="reports/")),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("is_ready", models.BooleanField(default=False)),
                (
                    "generation_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Generation time in seconds",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(unique=True)),
                ("period", models.CharField(default="daily", max_length=20)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "booking_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("successful_payments", models.PositiveIntegerField(default=0)),
                ("failed_payments", models.PositiveIntegerField(default=0)),
                ("properties_listed", models.PositiveIntegerField(default=0)),
                ("properties_rented", models.PositiveIntegerField(default=0)),
                ("properties_sold", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Revenue Analytics",
                "verbose_name_plural": "Revenue Analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "period"], name="analytics_r_date_846039_idx"
                    )
                ],
                "unique_together": {("date", "period")},
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_search_queries", models.PositiveIntegerField(default=0)),
                ("properties_viewed", models.PositiveIntegerField(default=0)),
                ("properties_favorited", models.PositiveIntegerField(default=0)),
                ("inquiries_sent", models.PositiveIntegerField(default=0)),
                ("bookings_made", models.PositiveIntegerField(default=0)),
                ("reviews_written", models.PositiveIntegerField(default=0)),
                (
                    "avg_session_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average session duration in minutes",
                        max_digits=8,
                    ),
                ),
                (
                    "bounce_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of single-page sessions",
                        max_digits=5,
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                (
                    "user_segment",
                    models.CharField(
                        blank=True,
                        help_text="User segmentation (e.g., 'active', 'casual', 'inactive')",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Analytics",
                "verbose_name_plural": "User Analytics",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("property_view", "Property View"),
                            ("search", "Search"),
                            ("inquiry", "Inquiry"),
                            ("booking", "Booking"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                            ("favorite", "Favorite"),
                            ("share", "Share"),
                            ("contact", "Contact"),
                            ("signup", "Sign Up"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                (
                    "event_data",
                    models.JSONField(default=dict, help_text="Additional event data"),
                ),
                ("url", models.URLField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_a_event_t_6c35be_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_a_user_id_ecb128_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="analytics_a_content_d0d251_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_a_session_8757e5_idx"
                    ),
                ],
            },
        ),
    ]
